(lang dune 2.9)
(using coq 0.3)
(name unit-test-propositional-v9)

(generate_opam_files true)

(package
  (name unit-test-propositional-v9)
  (version dev)
  (synopsis "unit test propositional dataset")
  (depends coq))
