(lang dune 2.9)
(using coq 0.3)
(name unit-test-chain-multi-v9)

(generate_opam_files true)

(package
  (name unit-test-chain-multi-v9)
  (version dev)
  (synopsis "unit test chain dataset")
  (depends coq))
